-- seeds/menu_seed.sql
CREATE DATABASE IF NOT EXISTS dineease;
USE dineease;

-- categories
CREATE TABLE IF NOT EXISTS categories (
  category_id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

-- menu items
CREATE TABLE IF NOT EXISTS menu_items (
  item_id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  description TEXT,
  price DECIMAL(8,2) NOT NULL,
  category_id INT,
  image_url VARCHAR(255),
  FOREIGN KEY (category_id) REFERENCES categories(category_id) ON DELETE SET NULL
);

-- clear existing rows (optional)
TRUNCATE TABLE categories;
TRUNCATE TABLE menu_items;

-- insert categories
INSERT INTO categories (name) VALUES
('Starters'),
('Main Course'),
('Desserts'),
('Drinks'),
('Pizza'),
('Burgers'),
('Pasta'),
('Asian'),
('Salads');

-- get category ids for convenience (not required to run)
-- Now insert many menu items (108 sample items)
INSERT INTO menu_items (name, description, price, category_id, image_url) VALUES
('Garlic Bread','Baked garlic bread with butter and herbs',3.50,1,'https://source.unsplash.com/400x300/?garlic-bread'),
('Bruschetta','Toasted bread topped with tomato and basil',4.25,1,'https://source.unsplash.com/400x300/?bruschetta'),
('Spring Rolls','Crispy vegetable spring rolls with dip',4.00,1,'https://source.unsplash.com/400x300/?spring-rolls'),
('Chicken Wings','Spicy chicken wings with BBQ glaze',6.50,1,'https://source.unsplash.com/400x300/?chicken-wings'),
('Paneer Tikka','Grilled paneer cubes marinated in spices',5.99,1,'https://source.unsplash.com/400x300/?paneer-tikka'),
('Margherita Pizza','Classic tomato, mozzarella, basil',8.99,5,'https://source.unsplash.com/400x300/?margherita-pizza'),
('Pepperoni Pizza','Pepperoni, tomato, mozzarella',9.99,5,'https://source.unsplash.com/400x300/?pepperoni-pizza'),
('BBQ Chicken Pizza','Smoky BBQ chicken, onions, cheese',10.99,5,'https://source.unsplash.com/400x300/?bbq-chicken-pizza'),
('Veggie Supreme Pizza','Mixed vegetables with rich cheese',9.49,5,'https://source.unsplash.com/400x300/?veggie-pizza'),
('Four Cheese Pizza','Mozzarella, cheddar, parmesan, gouda',11.50,5,'https://source.unsplash.com/400x300/?four-cheese-pizza'),
('Classic Burger','Beef patty, lettuce, tomato, cheese',7.99,6,'https://source.unsplash.com/400x300/?classic-burger'),
('Chicken Burger','Grilled chicken patty with lettuce and mayo',6.49,6,'https://source.unsplash.com/400x300/?chicken-burger'),
('Veggie Burger','Crispy vegetable patty with sauce',6.25,6,'https://source.unsplash.com/400x300/?veggie-burger'),
('Cheese Burst Burger','Extra cheese filled patty',8.25,6,'https://source.unsplash.com/400x300/?cheese-burger'),
('Bacon Deluxe','Beef bacon, cheese, smoky sauce',8.99,6,'https://source.unsplash.com/400x300/?bacon-burger'),
('Pasta Alfredo','Creamy Alfredo sauce with fettuccine',7.99,7,'https://source.unsplash.com/400x300/?pasta-alfredo'),
('Spaghetti Bolognese','Tomato meat sauce over spaghetti',8.50,7,'https://source.unsplash.com/400x300/?spaghetti-bolognese'),
('Penne Arrabiata','Spicy tomato sauce with penne',7.25,7,'https://source.unsplash.com/400x300/?penne-arrabbiata'),
('Lasagna','Layered pasta with meat and cheese',9.50,7,'https://source.unsplash.com/400x300/?lasagna'),
('Pesto Pasta','Basil pesto with pine nuts and parmesan',8.25,7,'https://source.unsplash.com/400x300/?pesto-pasta'),
('Chicken Fried Rice','Stir-fried rice with veggies and chicken',6.99,8,'https://source.unsplash.com/400x300/?fried-rice'),
('Veg Hakka Noodles','Stir-fried noodles with vegetables',6.50,8,'https://source.unsplash.com/400x300/?hakka-noodles'),
('Chicken Manchurian','Spicy chicken in tangy sauce',7.99,8,'https://source.unsplash.com/400x300/?chicken-manchurian'),
('Schezwan Noodles','Hot and spicy schezwan noodles',7.25,8,'https://source.unsplash.com/400x300/?schezwan-noodles'),
('Sweet Corn Soup','Creamy sweet corn soup',3.50,8,'https://source.unsplash.com/400x300/?sweet-corn-soup'),
('Caesar Salad','Romaine, parmesan, croutons, Caesar dressing',5.99,9,'https://source.unsplash.com/400x300/?caesar-salad'),
('Greek Salad','Cucumber, tomato, feta, olives',5.75,9,'https://source.unsplash.com/400x300/?greek-salad'),
('Quinoa Salad','Quinoa, roasted vegetables, vinaigrette',6.25,9,'https://source.unsplash.com/400x300/?quinoa-salad'),
('Fruit Salad','Seasonal fruits with honey drizzle',4.50,9,'https://source.unsplash.com/400x300/?fruit-salad'),
('Tandoori Chicken','Tandoor roasted chicken with spices',9.99,2,'https://source.unsplash.com/400x300/?tandoori-chicken'),
('Butter Chicken','Creamy tomato based chicken curry',9.50,2,'https://source.unsplash.com/400x300/?butter-chicken'),
('Dal Makhani','Slow-cooked lentils in buttery gravy',6.99,2,'https://source.unsplash.com/400x300/?dal-makhani'),
('Paneer Butter Masala','Cottage cheese in creamy tomato gravy',8.25,2,'https://source.unsplash.com/400x300/?paneer-butter-masala'),
('Rogan Josh','Fragrant lamb curry',11.99,2,'https://source.unsplash.com/400x300/?rogan-josh'),
('Chicken Biryani','Aromatic basmati rice with spiced chicken',10.99,2,'https://source.unsplash.com/400x300/?chicken-biryani'),
('Veg Biryani','Basmati rice cooked with vegetables and spices',8.99,2,'https://source.unsplash.com/400x300/?veg-biryani'),
('Hyderabadi Biryani','Authentic spiced biryani',12.50,2,'https://source.unsplash.com/400x300/?hyderabadi-biryani'),
('Mutton Biryani','Rich mutton biryani with layers of rice',13.99,2,'https://source.unsplash.com/400x300/?mutton-biryani'),
('Masala Dosa','Crispy dosa with potato masala',6.49,2,'https://source.unsplash.com/400x300/?masala-dosa'),
('Idli Sambar','Steamed rice cakes with sambar',4.99,2,'https://source.unsplash.com/400x300/?idli'),
('Vada Pav','Spiced potato sandwich',3.75,2,'https://source.unsplash.com/400x300/?vada-pav'),
('Pav Bhaji','Mashed vegetable curry with butter pav',5.50,2,'https://source.unsplash.com/400x300/?pav-bhaji'),
('Gulab Jamun','Soft milk dumplings in sugar syrup',3.25,3,'https://source.unsplash.com/400x300/?gulab-jamun'),
('Chocolate Brownie','Warm chocolate brownie with ice cream',4.50,3,'https://source.unsplash.com/400x300/?brownie'),
('Cheesecake','Creamy baked cheesecake',4.99,3,'https://source.unsplash.com/400x300/?cheesecake'),
('Tiramisu','Classic Italian coffee dessert',5.50,3,'https://source.unsplash.com/400x300/?tiramisu'),
('Kulfi Falooda','Traditional Indian ice cream dessert',4.25,3,'https://source.unsplash.com/400x300/?kulfi'),
('Mango Lassi','Sweet mango yogurt drink',2.99,4,'https://source.unsplash.com/400x300/?mango-lassi'),
('Fresh Lime Soda','Sparkling lime soda',1.99,4,'https://source.unsplash.com/400x300/?lime-soda'),
('Masala Chai','Indian spiced tea',1.50,4,'https://source.unsplash.com/400x300/?masala-chai'),
('Cold Coffee','Iced coffee with milk and sugar',2.50,4,'https://source.unsplash.com/400x300/?iced-coffee'),
('Orange Juice','Freshly squeezed orange juice',2.25,4,'https://source.unsplash.com/400x300/?orange-juice'),
('BBQ Ribs','Slow cooked ribs with BBQ glaze',13.99,2,'https://source.unsplash.com/400x300/?bbq-ribs'),
('Grilled Salmon','Salmon fillet with lemon butter',12.99,2,'https://source.unsplash.com/400x300/?grilled-salmon'),
('Steak Ribeye','Juicy ribeye steak grilled to perfection',16.50,2,'https://source.unsplash.com/400x300/?ribeye-steak'),
('Fish and Chips','Crispy battered fish with fries',9.25,2,'https://source.unsplash.com/400x300/?fish-and-chips'),
('Sushi Platter','Assorted sushi and sashimi',14.99,8,'https://source.unsplash.com/400x300/?sushi'),
('Tempura Veg','Lightly battered vegetable tempura',6.99,8,'https://source.unsplash.com/400x300/?tempura'),
('Ramen Bowl','Savory ramen with pork and egg',10.50,8,'https://source.unsplash.com/400x300/?ramen'),
('Gyoza','Pan-fried dumplings with dipping sauce',5.50,8,'https://source.unsplash.com/400x300/?gyoza'),
('Korean BBQ','Marinated meats grilled table-side',15.99,8,'https://source.unsplash.com/400x300/?korean-bbq'),
('Greek Gyro','Roasted meat wrap with tzatziki',7.99,6,'https://source.unsplash.com/400x300/?gyro'),
('Falafel Wrap','Crispy falafel with salad and sauce',6.25,6,'https://source.unsplash.com/400x300/?falafel'),
('Shawarma Plate','Tender shawarma with pita and salad',8.50,6,'https://source.unsplash.com/400x300/?shawarma'),
('Hummus Plate','Creamy chickpea dip with pita',4.50,6,'https://source.unsplash.com/400x300/?hummus'),
('Pancake Stack','Fluffy pancakes with maple syrup',5.25,3,'https://source.unsplash.com/400x300/?pancakes'),
('French Toast','Egg coated toast with berries',5.00,3,'https://source.unsplash.com/400x300/?french-toast'),
('Egg Benedict','Poached eggs on English muffin with hollandaise',6.75,3,'https://source.unsplash.com/400x300/?eggs-benedict'),
('Avocado Toast','Smashed avocado on sourdough',5.50,9,'https://source.unsplash.com/400x300/?avocado-toast'),
('Protein Bowl','Quinoa, chicken, greens, avocado',8.99,9,'https://source.unsplash.com/400x300/?protein-bowl'),
('Kebab Platter','Mixed kebabs with chutney',11.99,2,'https://source.unsplash.com/400x300/?kebab'),
('Samosa','Crispy pastry filled with spiced potatoes',2.50,1,'https://source.unsplash.com/400x300/?samosa'),
('Onion Rings','Crispy battered onion rings',3.99,1,'https://source.unsplash.com/400x300/?onion-rings'),
('Mozzarella Sticks','Cheesy fried sticks with dip',4.25,1,'https://source.unsplash.com/400x300/?mozzarella-sticks'),
('Loaded Fries','Fries with cheese, bacon and sauces',5.99,1,'https://source.unsplash.com/400x300/?loaded-fries'),
('Nachos','Crispy nachos with salsa and cheese',5.50,1,'https://source.unsplash.com/400x300/?nachos'),
('Stuffed Crust Pizza','Cheese stuffed crust with toppings',12.50,5,'https://source.unsplash.com/400x300/?stuffed-crust-pizza'),
('Hawaiian Pizza','Ham, pineapple and cheese',10.25,5,'https://source.unsplash.com/400x300/?hawaiian-pizza'),
('Carbonara','Classic creamy carbonara with pancetta',9.25,7,'https://source.unsplash.com/400x300/?carbonara'),
('Gnocchi','Potato gnocchi in tomato or cream sauce',8.50,7,'https://source.unsplash.com/400x300/?gnocchi'),
('Chicken Caesar Wrap','Grilled chicken with Caesar dressing in wrap',6.99,6,'https://source.unsplash.com/400x300/?chicken-wrap'),
('Tofu Stir Fry','Marinated tofu with seasonal veggies',7.50,8,'https://source.unsplash.com/400x300/?tofu-stir-fry'),
('Beef Stroganoff','Beef strips in creamy mushroom sauce',12.50,2,'https://source.unsplash.com/400x300/?beef-stroganoff'),
('Cajun Prawns','Spicy prawns in cajun seasoning',11.50,2,'https://source.unsplash.com/400x300/?cajun-prawns'),
('Lemon Tart','Tangy lemon tart with cream',4.25,3,'https://source.unsplash.com/400x300/?lemon-tart'),
('Chocolate Mousse','Light chocolate mousse',4.00,3,'https://source.unsplash.com/400x300/?chocolate-mousse'),
('Iced Tea','Refreshing brewed iced tea',1.99,4,'https://source.unsplash.com/400x300/?iced-tea'),
('Milkshake (Vanilla)','Creamy vanilla milkshake',3.50,4,'https://source.unsplash.com/400x300/?milkshake'),
('Soda (Coke)','Chilled cola drink',1.50,4,'https://source.unsplash.com/400x300/?cola'),
('Sparkling Water','Bubbly mineral water',1.25,4,'https://source.unsplash.com/400x300/?sparkling-water'),
('Matcha Latte','Smooth matcha with milk',3.75,4,'https://source.unsplash.com/400x300/?matcha-latte'),
('Pulled Pork Sandwich','Slow-cooked pulled pork in bun',9.99,6,'https://source.unsplash.com/400x300/?pulled-pork'),
('Veggie Quesadilla','Grilled quesadilla with cheese and veggies',6.50,1,'https://source.unsplash.com/400x300/?quesadilla'),
('Choco Chip Cookie','Fresh baked cookie with chocolate chips',1.75,3,'https://source.unsplash.com/400x300/?cookie'),
('Sushi Roll - California','Crab, avocado, cucumber roll',7.99,8,'https://source.unsplash.com/400x300/?california-roll'),
('Butter Naan','Soft Indian flatbread',1.25,2,'https://source.unsplash.com/400x300/?naan'),
('Raita','Yogurt dip with cucumber and spices',1.50,2,'https://source.unsplash.com/400x300/?raita'),
('Minestrone Soup','Hearty Italian vegetable soup',4.25,8,'https://source.unsplash.com/400x300/?minestrone'),
('Caprese Salad','Tomato, mozzarella, basil, olive oil',5.75,9,'https://source.unsplash.com/400x300/?caprese-salad'),
('Schezwan Fried Rice','Spicy fried rice with Schezwan flavors',7.25,8,'https://source.unsplash.com/400x300/?schezwan-fried-rice'),
('Beetroot Salad','Roasted beetroot with feta and greens',6.50,9,'https://source.unsplash.com/400x300/?beetroot-salad'),
('Chilli Paneer','Paneer cubes tossed in chili sauce',7.99,2,'https://source.unsplash.com/400x300/?chilli-paneer'),
('Creamy Mushroom Soup','Silky mushroom soup with herbs',4.50,8,'https://source.unsplash.com/400x300/?mushroom-soup'),
('Blueberry Muffin','Soft muffin loaded with blueberries',2.50,3,'https://source.unsplash.com/400x300/?blueberry-muffin'),
('Caramel Latte','Espresso with steamed milk and caramel',3.50,4,'https://source.unsplash.com/400x300/?caramel-latte'),
('Avocado Salad','Fresh avocado with greens and citrus',6.99,9,'https://source.unsplash.com/400x300/?avocado-salad'),
('Tandoori Prawns','Prawns marinated in tandoori spices',12.99,2,'https://source.unsplash.com/400x300/?tandoori-prawns'),
('Spinach Ravioli','Ravioli stuffed with ricotta and spinach',9.25,7,'https://source.unsplash.com/400x300/?ravioli'),
('Sweet Potato Fries','Crispy sweet potato fries',3.99,1,'https://source.unsplash.com/400x300/?sweet-potato-fries'),
('Ricotta Pancakes','Light ricotta pancakes with berries',5.99,3,'https://source.unsplash.com/400x300/?ricotta-pancakes'),
('Crispy Fish Tacos','Fish tacos with slaw and crema',8.50,2,'https://source.unsplash.com/400x300/?fish-tacos'),
('Falooda','Sweet rose-flavored dessert drink',3.50,3,'https://source.unsplash.com/400x300/?falooda'),
('Mochi Ice Cream','Chewy rice cake with ice cream center',3.75,3,'https://source.unsplash.com/400x300/?mochi-ice-cream'),
('Berry Smoothie','Mixed berry blended smoothie',3.25,4,'https://source.unsplash.com/400x300/?berry-smoothie'),
('Toffee Pudding','Warm toffee pudding with sauce',4.25,3,'https://source.unsplash.com/400x300/?toffee-pudding'),
('Coconut Water','Fresh coconut water',1.75,4,'https://source.unsplash.com/400x300/?coconut-water'),
('Paneer Roll','Spiced paneer rolled in flatbread',5.25,2,'https://source.unsplash.com/400x300/?paneer-roll'),
('Chicken Shawarma Wrap','Shawarma wrapped in soft flatbread',7.50,6,'https://source.unsplash.com/400x300/?shawarma-wrap');
